# Dependencies
markdown:         kramdown
# pygments:         true
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Aditya Jaishankar
tagline:          'Portfolio documents'
description:      'Listing of my portfolio changed'
url:              http://lanyon.getpoole.com

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/lanyon
