# Permalinks
permalink:           pretty
highlighter:         pygments

# Setup
title:               Aditya Jaishankar
tagline:             Portfolio
url:                 https://aditya-jaishankar.github.io/
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Aditya Jaishankar
  url:               https://aditya-jaishankar.github.io/

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/aditya-jaishankar/aditya-jaishankar.github.io

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Pages list that changes the links on the top of the website
pages_list:       {'About':'/about','Archive':'/archive','Feed':'/atom.xml'}
